{{- if and (not .Values.postgresql.enabled) .Values.postgresql.external.url }}
{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klask.fullname" . }}-postgresql-external
  labels:
    {{- include "klask.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  database-url: {{ .Values.postgresql.external.url | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if and .Values.backend.enabled (not .Values.backend.existingSecret) }}
{{- if or .Values.backend.secrets (and (not .Values.postgresql.enabled) .Values.backend.env.database.url) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "klask.fullname" . }}-backend
  labels:
    {{- include "klask.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{- if and (not .Values.postgresql.enabled) .Values.backend.env.database.url }}
  database-url: {{ .Values.backend.env.database.url | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
