{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "klask.fullname" . }}-backend
  labels:
    {{- include "klask.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  {{- if .Values.backend.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "klask.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "klask.labels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "klask.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
      initContainers:
        - name: init-permissions
          image: "{{ .Values.backend.busybox.image.repository }}:{{ .Values.backend.busybox.image.tag }}"
          command: ['sh', '-c', 'chown -R 1000:1000 /app/index && chmod -R 755 /app/index']
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
          volumeMounts:
            - name: index
              mountPath: /app/index
      {{- end }}
      containers:
        - name: backend
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["/scripts/entrypoint-wrapper.sh"]
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "klask.fullname" . }}-backend
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DB_HOST
              value: {{ include "klask.postgresql.servicename" . | quote }}
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "klask.postgresql.secretName" . }}
                  key: password
            {{- else if .Values.backend.env.database.url }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "klask.backend.secretName" . }}
                  key: database-url
            {{- end }}
            {{- range $key, $value := .Values.backend.env.customVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.backend.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.backend.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.backend.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
            - name: tmp
              mountPath: /tmp
            - name: index
              mountPath: /app/index
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "klask.fullname" . }}-backend
            defaultMode: 0755
            items:
              - key: entrypoint-wrapper.sh
                path: entrypoint-wrapper.sh
        {{- if and .Values.securityContext .Values.securityContext.readOnlyRootFilesystem }}
        - name: tmp
          {{- if .Values.backend.tmpPersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "klask.fullname" . }}-backend-tmp
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: cache
          emptyDir: {}
        - name: index
          {{- if .Values.backend.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "klask.fullname" . }}-backend-index
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
